apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app-2
  namespace: example-app-staging
spec:
  dnsNames:
    - example.koellgma.de
  secretName: example-app2-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer