resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: example-app
  literals:
    - STAGE="staging"
    - HOST_NAME="$(hostname)"

namespace: example-app-staging